// Master mantra dataset — 150+ mantras across all major dharmic traditions.
// Each entry: id, name, script, transliteration, meaning (en/hi), deity, tradition,
// category, benefits, howToChant, defaultMusic, language, featured.

export const ALL_MANTRAS = [
  // ───── SHAIVA ─────
  { id:'om-namah-shivaya', name:'Om Namah Shivaya', script:'ॐ नमः शिवाय', transliteration:'Om Namah Shivaya', meaning:'I bow to Shiva, the auspicious one. The five sacred syllables (Panchakshara).', meaningHindi:'मैं शिव को नमन करता हूँ। यह पंचाक्षर महामंत्र है।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Purifies the five elements within. Removes inner obstacles. Brings deep stillness and clarity.', howToChant:'Best on Mondays and Pradosham evenings. Use a Rudraksha mala. 108 repetitions.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:true },
  { id:'maha-mrityunjaya', name:'Maha Mrityunjaya Mantra', script:'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् । उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात् ॥', transliteration:'Om Tryambakam Yajamahe Sugandhim Pushtivardhanam Urvarukamiva Bandhanan Mrityor Mukshiya Maamritat', meaning:'We worship the three‑eyed Lord. May He free us from the bondage of death like a ripe fruit from its stem.', meaningHindi:'हम त्रिनेत्रधारी शिव की उपासना करते हैं — हमें मृत्यु के बन्धन से मुक्त करें।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Healing, longevity, protection from negative forces. Considered a moksha mantra.', howToChant:'108 repetitions, slowly and clearly, focusing on healing intention.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'shiv-panchakshara', name:'Shiv Panchakshara', script:'नमः शिवाय', transliteration:'Namah Shivaya', meaning:'Salutations to Shiva — the auspicious one.', meaningHindi:'मैं शिव को नमन करता हूँ।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Cleanses the five elements within. Aligns body, mind and spirit.', howToChant:'Continuous repetition while focusing on the heart center.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'om-tatpurushaya-vidmahe', name:'Om Tatpurushaya Vidmahe (Shiva Gayatri)', script:'ॐ तत्पुरुषाय विद्महे महादेवाय धीमहि । तन्नो रुद्रः प्रचोदयात् ॥', transliteration:'Om Tatpurushaya Vidmahe Mahadevaya Dhimahi Tanno Rudrah Prachodayat', meaning:'We meditate on the Supreme Being, the great Lord — may Rudra illuminate us.', meaningHindi:'हम महादेव का ध्यान करते हैं — रुद्र हमें प्रेरित करें।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Awakens awareness of Shiva consciousness; clears spiritual fog.', howToChant:'At Brahma Muhurta (pre‑dawn), 108 times.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'shiva-gayatri', name:'Shiva Gayatri', script:'ॐ पंचवक्त्राय विद्महे महादेवाय धीमहि । तन्नो रुद्रः प्रचोदयात् ॥', transliteration:'Om Panchavaktraya Vidmahe Mahadevaya Dhimahi Tanno Rudrah Prachodayat', meaning:'We meditate on the five‑faced Mahadeva — may Rudra inspire our intellect.', meaningHindi:'पंचमुखी महादेव का ध्यान करते हैं — रुद्र हमारी बुद्धि प्रेरित करें।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Inner courage, removal of fear, spiritual insight.', howToChant:'108 times at dawn, ideally facing east.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'om-namo-bhagavate-rudraya', name:'Om Namo Bhagavate Rudraya', script:'ॐ नमो भगवते रुद्राय', transliteration:'Om Namo Bhagavate Rudraya', meaning:'Salutations to Lord Rudra, the fierce form of Shiva.', meaningHindi:'मैं भगवान रुद्र को नमन करता हूँ।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Removes negativity; strengthens willpower and clarity.', howToChant:'Chant on Mondays and Saturdays. 108 repetitions.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'om-hara-hara-mahadeva', name:'Om Hara Hara Mahadeva', script:'ॐ हर हर महादेव', transliteration:'Om Hara Hara Mahadeva', meaning:'O Mahadeva, take away all that binds — destroyer of suffering.', meaningHindi:'हर हर महादेव — दुःखों के विनाशक भगवान शिव।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Energizing chant; instills courage and devotion.', howToChant:'Chant aloud with vigor; ideal for kanwariyas and Shiva bhakts.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'shambho-mahadeva', name:'Shambho Mahadeva', script:'शम्भो महादेव', transliteration:'Shambho Mahadeva', meaning:'O Shambho, O Mahadeva — the auspicious one.', meaningHindi:'शम्भो महादेव — कल्याणकारी शिव।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Brings auspiciousness and inner peace.', howToChant:'Soft, devotional repetition.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'bol-bam', name:'Bol Bam', script:'बोल बम', transliteration:'Bol Bam', meaning:'Speak/chant the name of Shiva (Bam‑Bhola).', meaningHindi:'बोल बम — भोलेनाथ का जयघोष।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Devotional energiser; common during Shravan kanwar yatra.', howToChant:'Loud, joyful repetition while walking or in groups.', defaultMusic:'shiv-tandav', language:'Hindi', featured:false },
  { id:'om-namo-nilakanthaya', name:'Om Namo Nilakanthaya', script:'ॐ नमो नीलकण्ठाय', transliteration:'Om Namo Nilakanthaya', meaning:'Salutations to the blue‑throated Lord (who drank the cosmic poison).', meaningHindi:'नीलकण्ठ शिव को नमन।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Said to neutralise inner toxicity and protect from harm.', howToChant:'108 times, especially during Mahashivratri.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'hara-hara-bole-namah-shivaya', name:'Hara Hara Bole Namah Shivaya', script:'हर हर बोले नमः शिवाय', transliteration:'Hara Hara Bole Namah Shivaya', meaning:'Chant Hara Hara — salutations to Shiva.', meaningHindi:'हर हर बोले — नमः शिवाय।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Joyful, energising chant of devotion.', howToChant:'Aloud, in kirtan style.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'om-shiv-om', name:'Om Shiv Om', script:'ॐ शिव ॐ', transliteration:'Om Shiv Om', meaning:'Om — Shiva — Om: the universal sound and the Lord.', meaningHindi:'ॐ शिव ॐ।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Simple, deep meditation chant.', howToChant:'Chant with breath: inhale Om, exhale Shiv Om.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },

  // ───── VAISHNAVA ─────
  { id:'om-namo-bhagavate-vasudevaya', name:'Om Namo Bhagavate Vasudevaya', script:'ॐ नमो भगवते वासुदेवाय', transliteration:'Om Namo Bhagavate Vasudevaya', meaning:'Salutations to Lord Vasudeva (Krishna), the all‑pervading.', meaningHindi:'मैं भगवान वासुदेव को नमन करता हूँ।', deity:'Vishnu', tradition:'Vaishnava', category:'vishnu', benefits:'Liberation, divine love, protection from worldly attachment.', howToChant:'108 times on a Tulsi mala, ideally at dawn.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'om-namo-narayanaya', name:'Om Namo Narayanaya', script:'ॐ नमो नारायणाय', transliteration:'Om Namo Narayanaya', meaning:'Salutations to Narayana — the resting place of all beings.', meaningHindi:'मैं नारायण को नमन करता हूँ।', deity:'Vishnu', tradition:'Vaishnava', category:'vishnu', benefits:'Brings peace, dissolves karmic burdens, opens the heart.', howToChant:'Repeat steadily with Tulsi mala.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'om-vishnave-namah', name:'Om Vishnave Namah', script:'ॐ विष्णवे नमः', transliteration:'Om Vishnave Namah', meaning:'Salutations to Vishnu — sustainer of the universe.', meaningHindi:'मैं विष्णु को नमन करता हूँ।', deity:'Vishnu', tradition:'Vaishnava', category:'vishnu', benefits:'Nurtures sustenance, harmony, and protection.', howToChant:'108 times on Thursdays.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'vishnu-gayatri', name:'Vishnu Gayatri', script:'ॐ नारायणाय विद्महे वासुदेवाय धीमहि । तन्नो विष्णुः प्रचोदयात् ॥', transliteration:'Om Narayanaya Vidmahe Vasudevaya Dhimahi Tanno Vishnuh Prachodayat', meaning:'We meditate on Narayana, on Vasudeva — may Vishnu inspire our intellect.', meaningHindi:'हम नारायण का ध्यान करते हैं — विष्णु हमारी बुद्धि प्रेरित करें।', deity:'Vishnu', tradition:'Vaishnava', category:'vishnu', benefits:'Awakens divine wisdom and equanimity.', howToChant:'108 times at sunrise.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'om-anantaya-namah', name:'Om Anantaya Namah', script:'ॐ अनन्ताय नमः', transliteration:'Om Anantaya Namah', meaning:'Salutations to the infinite one (Anant — Shesha Naga form of Vishnu).', meaningHindi:'अनन्त (शेषनाग) को नमन।', deity:'Vishnu', tradition:'Vaishnava', category:'vishnu', benefits:'Removes anxieties; expands consciousness.', howToChant:'On Anant Chaturdashi or daily.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'om-achyutaya-namah', name:'Om Achyutaya Namah', script:'ॐ अच्युताय नमः', transliteration:'Om Achyutaya Namah', meaning:'Salutations to the unfailing one — Achyuta (Krishna).', meaningHindi:'अच्युत भगवान को नमन।', deity:'Vishnu', tradition:'Vaishnava', category:'vishnu', benefits:'Stability of mind; constancy in devotion.', howToChant:'108 times daily.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },

  // ───── RAM ─────
  { id:'shri-ram-jai-ram', name:'Shri Ram Jai Ram Jai Jai Ram', script:'श्री राम जय राम जय जय राम', transliteration:'Shri Ram Jai Ram Jai Jai Ram', meaning:'Glory to Lord Ram — repeated victory chant of devotion.', meaningHindi:'श्री राम की जय हो — विजय का उद्घोष।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Energises mind; brings courage, removes negativity.', howToChant:'Repeat continuously, 108 times.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:true },
  { id:'ram-ram', name:'Ram Ram', script:'राम राम', transliteration:'Ram Ram', meaning:'The simple, supreme name of Lord Ram.', meaningHindi:'राम राम — सर्वोच्च नाम स्मरण।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Peace, focus, gradual liberation.', howToChant:'Continuously throughout the day.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:true },
  { id:'jai-shri-ram', name:'Jai Shri Ram', script:'जय श्री राम', transliteration:'Jai Shri Ram', meaning:'Victory to Lord Ram.', meaningHindi:'जय श्री राम।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Awakens devotion and courage.', howToChant:'Aloud with enthusiasm.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:false },
  { id:'sita-ram', name:'Sita Ram', script:'सीता राम', transliteration:'Sita Ram', meaning:'Joint name of the divine couple Sita and Ram.', meaningHindi:'सीता राम — दैवी युगल का स्मरण।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Harmonises relationships; brings home peace.', howToChant:'Soft repetition while walking or sleeping.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:false },
  { id:'om-sri-ramaya-namah', name:'Om Sri Ramaya Namah', script:'ॐ श्री रामाय नमः', transliteration:'Om Sri Ramaya Namah', meaning:'Salutations to Sri Ram.', meaningHindi:'श्री राम को नमन।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Removes obstacles; fosters dharma.', howToChant:'108 times daily.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:false },
  { id:'ram-naam-satya-hai', name:'Ram Naam Satya Hai', script:'राम नाम सत्य है', transliteration:'Ram Naam Satya Hai', meaning:'The name of Ram is the only truth.', meaningHindi:'राम नाम ही सत्य है।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Detachment from impermanent concerns; remembrance of truth.', howToChant:'Chant gently and reflect.', defaultMusic:'ram-dhun', language:'Hindi', featured:false },
  { id:'ramchandra-ki-jai', name:'Ramchandra Ki Jai', script:'रामचंद्र की जय', transliteration:'Ramchandra Ki Jai', meaning:'Victory to Lord Ramchandra.', meaningHindi:'रामचंद्र की जय।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Joyful awakening of devotion.', howToChant:'Aloud.', defaultMusic:'ram-dhun', language:'Hindi', featured:false },
  { id:'om-dasharathaya-namah', name:'Om Dasharathaya Namah', script:'ॐ दशरथाय नमः', transliteration:'Om Dasharathaya Namah', meaning:'Salutations to King Dasharatha (father of Ram).', meaningHindi:'राजा दशरथ को नमन।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Honors the lineage of Ram.', howToChant:'108 times.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:false },
  { id:'sri-rama-rama-rameti', name:'Sri Rama Rama Rameti', script:'श्री राम राम रामेति रमे रामे मनोरमे । सहस्रनाम तत्तुल्यं रामनाम वरानने ॥', transliteration:'Sri Rama Rama Rameti Rame Rame Manorame Sahasranama Tattulyam Rama Nama Varanane', meaning:'O lovely one — chanting Ram thrice equals reciting the thousand names of Vishnu.', meaningHindi:'राम नाम के तीन उच्चारण से सहस्रनाम का फल मिलता है।', deity:'Ram', tradition:'Vaishnava', category:'ram', benefits:'Said to be equal to reciting Vishnu Sahasranama.', howToChant:'Recite thrice — Ram Ram Rameti.', defaultMusic:'ram-dhun', language:'Sanskrit', featured:false },

  // ───── KRISHNA / RADHE ─────
  { id:'hare-krishna-mahamantra', name:'Hare Krishna Mahamantra', script:'हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे । हरे राम हरे राम राम राम हरे हरे ॥', transliteration:'Hare Krishna Hare Krishna Krishna Krishna Hare Hare / Hare Ram Hare Ram Ram Ram Hare Hare', meaning:'The 16‑word great chant for the age of Kali — calling on Krishna and Ram.', meaningHindi:'कलियुग का महामन्त्र — कृष्ण और राम का नाम स्मरण।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Spiritual awakening; love and joy; union with the Supreme.', howToChant:'One round = 108 repetitions of the full 16 words on a Tulsi mala.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:true },
  { id:'radhe-radhe', name:'Radhe Radhe', script:'राधे राधे', transliteration:'Radhe Radhe', meaning:'A loving repetition of Radha\'s name — the supreme bhakti.', meaningHindi:'राधे राधे — श्री राधा का प्रेम स्मरण।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Awakens madhurya bhava; sweetens speech; cultivates devotion.', howToChant:'Use as greeting and continuous japa.', defaultMusic:'radhe-chant', language:'Sanskrit', featured:true },
  { id:'radhe-krishna', name:'Radhe Krishna', script:'राधे कृष्ण', transliteration:'Radhe Krishna', meaning:'The eternal divine couple — supreme love and grace.', meaningHindi:'राधे कृष्ण — दिव्य प्रेम का स्वरूप।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Awakens love and surrender.', howToChant:'Soft continuous repetition.', defaultMusic:'radhe-chant', language:'Sanskrit', featured:false },
  { id:'om-namo-bhagavate-krishnaya', name:'Om Namo Bhagavate Krishnaya', script:'ॐ नमो भगवते कृष्णाय', transliteration:'Om Namo Bhagavate Krishnaya', meaning:'Salutations to Lord Krishna.', meaningHindi:'भगवान कृष्ण को नमन।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Removes ego; cultivates surrender.', howToChant:'108 times on a Tulsi mala.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'krishna-govinda-hari-murari', name:'Krishna Govinda Hari Murari', script:'कृष्ण गोविंद हरि मुरारी', transliteration:'Krishna Govinda Hari Murari', meaning:'Calling Krishna by his many beloved names.', meaningHindi:'कृष्ण के विभिन्न प्रिय नामों का स्मरण।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Joyful kirtan; melts the heart.', howToChant:'Aloud, in melody.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'om-krishnaya-namah', name:'Om Krishnaya Namah', script:'ॐ कृष्णाय नमः', transliteration:'Om Krishnaya Namah', meaning:'Salutations to Krishna.', meaningHindi:'कृष्ण को नमन।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Awakens love; removes inner blockages.', howToChant:'108 times.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'jai-shri-krishna', name:'Jai Shri Krishna', script:'जय श्री कृष्ण', transliteration:'Jai Shri Krishna', meaning:'Victory to Lord Krishna.', meaningHindi:'जय श्री कृष्ण।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Joy, lightness, devotion.', howToChant:'As greeting and as chant.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'govinda-jai-jai', name:'Govinda Jai Jai Gopal Jai Jai', script:'गोविंद जय जय गोपाल जय जय', transliteration:'Govinda Jai Jai Gopal Jai Jai', meaning:'Victory to Govinda, victory to Gopal — names of Krishna.', meaningHindi:'गोविंद और गोपाल की जय।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Energetic devotional kirtan.', howToChant:'Sing in melody.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'om-govindaya-namah', name:'Om Govindaya Namah', script:'ॐ गोविंदाय नमः', transliteration:'Om Govindaya Namah', meaning:'Salutations to Govinda — protector of cows and devotees.', meaningHindi:'गोविंद को नमन।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Cultivates compassion; brings prosperity.', howToChant:'108 times.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'jai-jai-radhe-shyam', name:'Jai Jai Radhe Shyam', script:'जय जय राधे श्याम', transliteration:'Jai Jai Radhe Shyam', meaning:'Victory to Radhe and Shyam — the divine couple.', meaningHindi:'राधे श्याम की जय।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Sweet remembrance of divine love.', howToChant:'Sing softly with melody.', defaultMusic:'radhe-chant', language:'Sanskrit', featured:false },
  { id:'om-klim-krishnaya-namah', name:'Om Klim Krishnaya Namah', script:'ॐ क्लीं कृष्णाय नमः', transliteration:'Om Klim Krishnaya Namah', meaning:'Beej mantra invoking the attractive form of Krishna.', meaningHindi:'क्लीं बीज सहित कृष्ण को नमन।', deity:'Krishna', tradition:'Vaishnava', category:'krishna', benefits:'Attracts grace, love, and well‑being.', howToChant:'108 times in early morning.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },

  // ───── HANUMAN ─────
  { id:'om-han-hanumate-namah', name:'Om Han Hanumate Namah', script:'ॐ हं हनुमते नमः', transliteration:'Om Han Hanumate Namah', meaning:'Beej mantra of Hanuman — strength and devotion.', meaningHindi:'हनुमान जी का बीज मन्त्र।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Removes fear; grants strength; dispels negativity.', howToChant:'Tuesday and Saturday with red sandalwood mala.', defaultMusic:'hanuman', language:'Sanskrit', featured:true },
  { id:'jai-bajrang-bali', name:'Jai Bajrang Bali', script:'जय बजरंग बली', transliteration:'Jai Bajrang Bali', meaning:'Victory to the thunderbolt‑bodied (Hanuman).', meaningHindi:'बजरंग बली की जय।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Awakens courage and protective energy.', howToChant:'Aloud with vigor.', defaultMusic:'hanuman', language:'Hindi', featured:false },
  { id:'om-anjaneyaya-namah', name:'Om Anjaneyaya Namah', script:'ॐ अञ्जनेयाय नमः', transliteration:'Om Anjaneyaya Namah', meaning:'Salutations to the son of Anjana (Hanuman).', meaningHindi:'अञ्जनी पुत्र हनुमान को नमन।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Strength, devotion, removal of obstacles.', howToChant:'108 times.', defaultMusic:'hanuman', language:'Sanskrit', featured:false },
  { id:'hanuman-gayatri', name:'Hanuman Gayatri', script:'ॐ आञ्जनेयाय विद्महे वायुपुत्राय धीमहि । तन्नो हनुमत् प्रचोदयात् ॥', transliteration:'Om Anjaneyaya Vidmahe Vayuputraya Dhimahi Tanno Hanumat Prachodayat', meaning:'We meditate on Hanuman, son of Vayu — may he inspire our intellect.', meaningHindi:'वायुपुत्र हनुमान का ध्यान — वे हमें प्रेरित करें।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Awakens vigor and discernment.', howToChant:'108 times at dawn.', defaultMusic:'hanuman', language:'Sanskrit', featured:false },
  { id:'om-hanumate-rudraya-namah', name:'Om Hanumate Rudraya Namah', script:'ॐ हनुमते रुद्राय नमः', transliteration:'Om Hanumate Rudraya Namah', meaning:'Hanuman as the eleventh Rudra — fierce protector.', meaningHindi:'रुद्र अवतार हनुमान को नमन।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Strong protection; removes fear and negative forces.', howToChant:'Tuesday/Saturday.', defaultMusic:'hanuman', language:'Sanskrit', featured:false },
  { id:'bajrang-baan-beej', name:'Bajrang Baan Beej Mantra', script:'ॐ ह्रीं हनुमते नमः', transliteration:'Om Hreem Hanumate Namah', meaning:'Beej form of Bajrang Baan — invokes intense protection.', meaningHindi:'बजरंग बाण का बीज मन्त्र।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Fast removal of obstacles; protection from harm.', howToChant:'108 times with focus.', defaultMusic:'hanuman', language:'Sanskrit', featured:false },
  { id:'jai-hanuman-gyan-gun-sagar', name:'Jai Hanuman Gyan Gun Sagar', script:'जय हनुमान ज्ञान गुण सागर', transliteration:'Jai Hanuman Gyan Gun Sagar', meaning:'Glory to Hanuman, ocean of wisdom and virtues (Hanuman Chalisa opening).', meaningHindi:'जय हनुमान, ज्ञान गुणों के सागर।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Devotional opening; sets the heart for Chalisa.', howToChant:'Sing as kirtan.', defaultMusic:'hanuman', language:'Hindi', featured:false },
  { id:'pawanputra-hanuman-ki-jai', name:'Pawanputra Hanuman Ki Jai', script:'पवनपुत्र हनुमान की जय', transliteration:'Pawanputra Hanuman Ki Jai', meaning:'Glory to the son of the Wind, Hanuman.', meaningHindi:'पवनपुत्र हनुमान की जय।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Energising chant of victory.', howToChant:'Aloud.', defaultMusic:'hanuman', language:'Hindi', featured:false },
  { id:'om-mahaveera-hanumate-namah', name:'Om Mahaveera Hanumate Namah', script:'ॐ महावीर हनुमते नमः', transliteration:'Om Mahaveera Hanumate Namah', meaning:'Salutations to the great hero Hanuman.', meaningHindi:'महावीर हनुमान को नमन।', deity:'Hanuman', tradition:'Vaishnava', category:'hanuman', benefits:'Strength, valor and devotion.', howToChant:'108 times.', defaultMusic:'hanuman', language:'Sanskrit', featured:false },

  // ───── GANESHA ─────
  { id:'om-gam-ganapataye-namah', name:'Om Gam Ganapataye Namah', script:'ॐ गं गणपतये नमः', transliteration:'Om Gam Ganapataye Namah', meaning:'Beej‑seed mantra invoking Ganesha — remover of obstacles.', meaningHindi:'गणपति को नमन — विघ्नहर्ता।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Removes obstacles; brings wisdom and success.', howToChant:'Before any new beginning, especially Wednesdays.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'vakratunda-mahakaya', name:'Vakratunda Mahakaya', script:'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ । निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा ॥', transliteration:'Vakratunda Mahakaya Suryakoti Samaprabha Nirvighnam Kuru Me Deva Sarvakaryeshu Sarvada', meaning:'O Lord with curved trunk and great body, brilliant as a million suns — make all my work obstacle‑free.', meaningHindi:'वक्रतुण्ड, महाकाय, सूर्यकोटि के समान तेज वाले — सर्व कार्य निर्विघ्न करें।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Begin every task with this prayer.', howToChant:'Once or 11 times before new ventures.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'om-gan-ganpataye-namo-namah', name:'Om Gan Ganpataye Namo Namah', script:'ॐ गण गणपतये नमो नमः', transliteration:'Om Gan Ganpataye Namo Namah', meaning:'Salutations again and again to Ganapati.', meaningHindi:'गणपति को बारम्बार नमन।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Invokes auspicious beginnings.', howToChant:'108 times.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'ganesh-gayatri', name:'Ganesh Gayatri', script:'ॐ एकदन्ताय विद्महे वक्रतुण्डाय धीमहि । तन्नो दन्तिः प्रचोदयात् ॥', transliteration:'Om Ekadantaya Vidmahe Vakratundaya Dhimahi Tanno Dantih Prachodayat', meaning:'We meditate on the one‑tusked Lord — may He illuminate our intellect.', meaningHindi:'एकदन्त गणेश का ध्यान।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Awakens wisdom and clarity.', howToChant:'108 times at dawn.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'om-vighna-nashaya-namah', name:'Om Vighna Nashaya Namah', script:'ॐ विघ्ननाशाय नमः', transliteration:'Om Vighna Nashaya Namah', meaning:'Salutations to the destroyer of obstacles.', meaningHindi:'विघ्नों के नाशक को नमन।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Removes problems; brings smooth flow.', howToChant:'108 times.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'jai-ganesh-jai-ganesh-deva', name:'Jai Ganesh Jai Ganesh Deva', script:'जय गणेश जय गणेश जय गणेश देवा', transliteration:'Jai Ganesh Jai Ganesh Deva', meaning:'Victory to Lord Ganesh — beloved aarti opening.', meaningHindi:'जय गणेश देवा — आरती।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Devotional joy.', howToChant:'Aarti style.', defaultMusic:'om-chant', language:'Hindi', featured:false },
  { id:'om-lambodharaya-namah', name:'Om Lambodharaya Namah', script:'ॐ लम्बोदराय नमः', transliteration:'Om Lambodharaya Namah', meaning:'Salutations to the round‑bellied one.', meaningHindi:'लम्बोदर गणेश को नमन।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Brings sufficiency and contentment.', howToChant:'108 times.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'gajanana-shri-ganaraya', name:'Gajanana Shri Ganaraya', script:'गजानना श्री गणराया', transliteration:'Gajanana Shri Ganaraya', meaning:'Elephant‑faced Lord, leader of the ganas.', meaningHindi:'गजानन गणपति को नमन।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Joyful Marathi devotional chant.', howToChant:'Sing in melody.', defaultMusic:'om-chant', language:'Marathi', featured:false },
  { id:'sukhakarta-dukhaharta', name:'Sukhakarta Dukhaharta', script:'सुखकर्ता दुःखहर्ता वार्ता विघ्नाची', transliteration:'Sukhakarta Dukhaharta', meaning:'Bringer of joy, remover of sorrow — Ganesh aarti.', meaningHindi:'सुखों के कर्ता और दुःखों के हर्ता।', deity:'Ganesha', tradition:'Universal', category:'ganesha', benefits:'Auspicious daily aarti.', howToChant:'Sing.', defaultMusic:'om-chant', language:'Marathi', featured:false },

  // ───── DEVI / DURGA / SHAKTI ─────
  { id:'om-dum-durgayai-namah', name:'Om Dum Durgayai Namah', script:'ॐ दुं दुर्गायै नमः', transliteration:'Om Dum Durgayai Namah', meaning:'Beej mantra of Goddess Durga.', meaningHindi:'माँ दुर्गा को नमन।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Protection from negativity; courage; victory over inner demons.', howToChant:'During Navratri or Tuesdays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-aim-hrim-klim-chamundaye', name:'Om Aim Hrim Klim Chamundaye Viche', script:'ॐ ऐं ह्रीं क्लीं चामुण्डायै विच्चे', transliteration:'Om Aim Hrim Klim Chamundaye Viche', meaning:'The supreme Devi mantra (Navarna) for divine protection.', meaningHindi:'दुर्गा सप्तशती का नवार्ण मन्त्र।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Powerful protection; awakens kundalini shakti.', howToChant:'108 times during Navratri.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'jai-mata-di', name:'Jai Mata Di', script:'जय माता दी', transliteration:'Jai Mata Di', meaning:'Victory to the Divine Mother.', meaningHindi:'माँ की जय।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Devotional energizer.', howToChant:'Aloud.', defaultMusic:'gayatri', language:'Hindi', featured:false },
  { id:'ya-devi-sarva-bhuteshu', name:'Ya Devi Sarva Bhuteshu', script:'या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता । नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः ॥', transliteration:'Ya Devi Sarva Bhuteshu Shaktirupena Samsthita Namastasyai Namastasyai Namastasyai Namo Namah', meaning:'Salutations to the Devi who resides in all beings as Shakti.', meaningHindi:'सर्वभूतों में शक्तिरूप से स्थित देवी को बार-बार नमन।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Awakens reverence for the divine feminine within all.', howToChant:'During Devi puja or Navratri.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'durga-gayatri', name:'Durga Gayatri', script:'ॐ कात्यायनाय विद्महे कन्यकुमारि धीमहि । तन्नो दुर्गिः प्रचोदयात् ॥', transliteration:'Om Katyayanaya Vidmahe Kanyakumari Dhimahi Tanno Durgih Prachodayat', meaning:'We meditate on Katyayani — may Durga inspire our intellect.', meaningHindi:'कात्यायनी का ध्यान।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Blessing of the Divine Mother.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'navarna-mantra', name:'Navarna Mantra', script:'ॐ ऐं ह्रीं क्लीं', transliteration:'Om Aim Hrim Klim', meaning:'Beej syllables invoking Saraswati, Lakshmi and Kali respectively.', meaningHindi:'सरस्वती, लक्ष्मी, काली के बीज।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Awakens balanced shakti.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'sarva-mangala-mangalye', name:'Sarva Mangala Mangalye', script:'सर्वमंगलमांगल्ये शिवे सर्वार्थसाधिके । शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तुते ॥', transliteration:'Sarva Mangala Mangalye Shive Sarvartha Sadhike Sharanye Tryambake Gauri Narayani Namostute', meaning:'Salutations to the Mother who is the source of all auspiciousness and refuge.', meaningHindi:'सर्व मंगल की दात्री देवी को नमन।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Brings auspiciousness in all endeavors.', howToChant:'In Devi Suktam or daily.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-chandikayai-namah', name:'Om Chandikayai Namah', script:'ॐ चण्डिकायै नमः', transliteration:'Om Chandikayai Namah', meaning:'Salutations to Chandika — fierce form of the Goddess.', meaningHindi:'चण्डिका माता को नमन।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Removes fear and negative forces.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'sherawali-mata-ki-jai', name:'Sherawali Mata Ki Jai', script:'शेरावाली माता की जय', transliteration:'Sherawali Mata Ki Jai', meaning:'Victory to the Mother who rides the lion.', meaningHindi:'शेरावाली माँ की जय।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Devotional energizer.', howToChant:'Aloud.', defaultMusic:'gayatri', language:'Hindi', featured:false },

  // ───── LAKSHMI ─────
  { id:'om-shreem-mahalakshmyai-namah', name:'Om Shreem Mahalakshmyai Namah', script:'ॐ श्रीं महालक्ष्म्यै नमः', transliteration:'Om Shreem Mahalakshmyai Namah', meaning:'Salutations to Mahalakshmi — bringer of prosperity and grace.', meaningHindi:'महालक्ष्मी को नमन।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Attracts abundance, grace, and harmonious relationships.', howToChant:'Friday is sacred. Light a ghee lamp and chant 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-shri-lakshmiye-namah', name:'Om Shri Lakshmiye Namah', script:'ॐ श्री लक्ष्म्यै नमः', transliteration:'Om Shri Lakshmiye Namah', meaning:'Salutations to Goddess Lakshmi.', meaningHindi:'देवी लक्ष्मी को नमन।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Brings sufficiency and contentment.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'lakshmi-gayatri', name:'Lakshmi Gayatri', script:'ॐ महालक्ष्म्यै विद्महे विष्णुपत्न्यै धीमहि । तन्नो लक्ष्मीः प्रचोदयात् ॥', transliteration:'Om Mahalakshmyai Vidmahe Vishnupatnyai Dhimahi Tanno Lakshmih Prachodayat', meaning:'We meditate on Mahalakshmi, consort of Vishnu — may she inspire us.', meaningHindi:'महालक्ष्मी का ध्यान।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Awakens prosperity consciousness.', howToChant:'108 times on Fridays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-hrim-shrim-lakshmibhyo-namah', name:'Om Hrim Shrim Lakshmibhyo Namah', script:'ॐ ह्रीं श्रीं लक्ष्मीभ्यो नमः', transliteration:'Om Hrim Shrim Lakshmibhyo Namah', meaning:'Beej‑seed combination invoking Lakshmi.', meaningHindi:'लक्ष्मी जी के बीज मन्त्र।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Removes financial obstacles.', howToChant:'108 times on Fridays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'shreem-brzee', name:'Shreem Brzee', script:'श्रीं ब्रज़ी', transliteration:'Shreem Brzee', meaning:'Modern abundance mantra (taught by Dr. Pillai).', meaningHindi:'समृद्धि का बीज।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Cultivates abundance mindset.', howToChant:'108 times daily.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-kamala-kamalalayai-namah', name:'Om Kamala Kamalalayai Namah', script:'ॐ कमल कमलालयै नमः', transliteration:'Om Kamala Kamalalayai Namah', meaning:'Salutations to the lotus‑seated Kamala (Lakshmi).', meaningHindi:'कमलासना लक्ष्मी को नमन।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Beauty, grace, and sustenance.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },

  // ───── SARASWATI ─────
  { id:'om-aim-saraswatyai-namah', name:'Om Aim Saraswatyai Namah', script:'ॐ ऐं सरस्वत्यै नमः', transliteration:'Om Aim Saraswatyai Namah', meaning:'Salutations to Saraswati — bestower of knowledge.', meaningHindi:'सरस्वती को नमन।', deity:'Saraswati', tradition:'Shakta', category:'devi', benefits:'Sharpens intellect, inspires creativity, enhances speech.', howToChant:'Before study or creative work.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'saraswati-gayatri', name:'Saraswati Gayatri', script:'ॐ सरस्वत्यै विद्महे ब्रह्मपुत्र्यै धीमहि । तन्नो देवी प्रचोदयात् ॥', transliteration:'Om Saraswatyai Vidmahe Brahmaputryai Dhimahi Tanno Devi Prachodayat', meaning:'We meditate on Saraswati — may the Goddess inspire us.', meaningHindi:'सरस्वती का ध्यान।', deity:'Saraswati', tradition:'Shakta', category:'devi', benefits:'Awakens wisdom and learning.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'ya-kundendu-tushara', name:'Ya Kundendu Tushara', script:'या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता । या वीणावरदण्डमण्डितकरा या श्वेतपद्मासना ॥', transliteration:'Ya Kundendu Tusharahara Dhavala Ya Shubhravastravrita', meaning:'Hymn to Saraswati — fair as jasmine, moon and snow.', meaningHindi:'सरस्वती की वन्दना।', deity:'Saraswati', tradition:'Shakta', category:'devi', benefits:'Awakens learning and grace.', howToChant:'During study or Vasant Panchami.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-vagdevyai-namah', name:'Om Vagdevyai Namah', script:'ॐ वाग्देव्यै नमः', transliteration:'Om Vagdevyai Namah', meaning:'Salutations to the Goddess of speech (Saraswati).', meaningHindi:'वाग्देवी को नमन।', deity:'Saraswati', tradition:'Shakta', category:'devi', benefits:'Refines speech and articulation.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },

  // ───── SURYA ─────
  { id:'gayatri-mantra', name:'Gayatri Mantra', script:'ॐ भूर्भुवः स्वः । तत्सवितुर्वरेण्यं । भर्गो देवस्य धीमहि । धियो यो नः प्रचोदयात् ॥', transliteration:'Om Bhur Bhuvah Svah Tat Savitur Varenyam Bhargo Devasya Dhimahi Dhiyo Yo Nah Prachodayat', meaning:'We meditate upon the radiance of the divine Sun — may it illuminate our intellect.', meaningHindi:'सूर्यदेव की दिव्यता का ध्यान — वे हमारी बुद्धि को प्रेरित करें।', deity:'Surya', tradition:'Vedic', category:'surya', benefits:'Awakens wisdom; purifies the mind; brings clarity.', howToChant:'At sunrise, noon, sunset (Sandhya). Face east at dawn.', defaultMusic:'gayatri', language:'Sanskrit', featured:true },
  { id:'om-suryaya-namah', name:'Om Suryaya Namah', script:'ॐ सूर्याय नमः', transliteration:'Om Suryaya Namah', meaning:'Salutations to the Sun God.', meaningHindi:'सूर्यदेव को नमन।', deity:'Surya', tradition:'Vedic', category:'surya', benefits:'Vitality, leadership, clarity.', howToChant:'At sunrise with Surya Namaskar.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-adityaya-namah', name:'Om Adityaya Namah', script:'ॐ आदित्याय नमः', transliteration:'Om Adityaya Namah', meaning:'Salutations to Aditya (the Sun).', meaningHindi:'आदित्य को नमन।', deity:'Surya', tradition:'Vedic', category:'surya', benefits:'Vitality and good health.', howToChant:'108 times at sunrise.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-hraam-hreem-hraum-suryaya', name:'Om Hraam Hreem Hraum Sah Suryaya Namah', script:'ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः', transliteration:'Om Hraam Hreem Hraum Sah Suryaya Namah', meaning:'Beej‑seed combination invoking Surya.', meaningHindi:'सूर्य के बीज मन्त्र।', deity:'Surya', tradition:'Vedic', category:'surya', benefits:'Strengthens Sun in horoscope; brings vitality.', howToChant:'At sunrise on Sundays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'surya-gayatri', name:'Surya Gayatri', script:'ॐ भास्कराय विद्महे महातेजाय धीमहि । तन्नो सूर्यः प्रचोदयात् ॥', transliteration:'Om Bhaskaraya Vidmahe Mahatejaya Dhimahi Tanno Suryah Prachodayat', meaning:'We meditate on Bhaskara — may the Sun inspire us.', meaningHindi:'भास्कर का ध्यान।', deity:'Surya', tradition:'Vedic', category:'surya', benefits:'Awakens vitality and clarity.', howToChant:'108 times at sunrise.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'aditya-hridayam-seed', name:'Aditya Hridayam Seed Mantra', script:'ॐ घृणि सूर्य आदित्य', transliteration:'Om Ghrini Surya Aditya', meaning:'Heart of the Sun — beej from Aditya Hridayam Stotra.', meaningHindi:'आदित्य हृदयम् का बीज।', deity:'Surya', tradition:'Vedic', category:'surya', benefits:'Vitality, courage, victory.', howToChant:'At sunrise.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },

  // ───── UNIVERSAL / VEDIC ─────
  { id:'om', name:'Om', script:'ॐ', transliteration:'Om / Aum', meaning:'The primordial sound — A‑U‑M — represents creation, preservation, and dissolution.', meaningHindi:'ॐ — सम्पूर्ण सृष्टि का मूल नाद।', deity:'Universal', tradition:'Universal', category:'universal', benefits:'Calms the nervous system, deepens focus, regulates breath.', howToChant:'Long, slow exhalation. Inhale; chant Om for the entire breath.', defaultMusic:'om-chant', language:'Sanskrit', featured:true },
  { id:'om-shanti-shanti-shanti', name:'Om Shanti Shanti Shanti', script:'ॐ शान्तिः शान्तिः शान्तिः', transliteration:'Om Shanti Shanti Shanti', meaning:'Peace in body, mind, and spirit.', meaningHindi:'त्रिविध शान्ति — आधिभौतिक, आधिदैविक, आध्यात्मिक।', deity:'Universal', tradition:'Universal', category:'universal', benefits:'Closing prayer for any sadhana.', howToChant:'After meditation or yoga.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'soham', name:'So Hum', script:'सोऽहम्', transliteration:'So Hum', meaning:'I am That — the natural breath mantra.', meaningHindi:'मैं वही ब्रह्म हूँ।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'Deep stillness; identification with the Self.', howToChant:'Inhale: So. Exhale: Hum.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'aham-brahmasmi', name:'Aham Brahmasmi', script:'अहं ब्रह्मास्मि', transliteration:'Aham Brahmasmi', meaning:'I am Brahman — I am the infinite Self.', meaningHindi:'मैं ब्रह्म हूँ।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'Awakens the Mahavakya — direct realization.', howToChant:'In silent contemplation.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'tat-tvam-asi', name:'Tat Tvam Asi', script:'तत् त्वम् असि', transliteration:'Tat Tvam Asi', meaning:'Thou art That — you are the Absolute (Mahavakya from Chandogya).', meaningHindi:'तुम वही (ब्रह्म) हो।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'One of the four great statements (Mahavakyas).', howToChant:'In silent contemplation.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'om-tat-sat', name:'Om Tat Sat', script:'ॐ तत् सत्', transliteration:'Om Tat Sat', meaning:'Om — That — Truth (Bhagavad Gita 17.23).', meaningHindi:'ॐ तत् सत् — गीता का परम सूत्र।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'Sanctifies all action.', howToChant:'Used to consecrate offerings and actions.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'shivoham', name:'Shivoham', script:'शिवोऽहम्', transliteration:'Shivoham', meaning:'I am Shiva — pure consciousness.', meaningHindi:'मैं शिव हूँ।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'Awakens pure awareness.', howToChant:'In meditative silence.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'om-purnamadah-purnamidam', name:'Om Purnamadah Purnamidam', script:'ॐ पूर्णमदः पूर्णमिदम् पूर्णात्पूर्णमुदच्यते । पूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते ॥', transliteration:'Om Purnamadah Purnamidam Purnat Purnamudachyate Purnasya Purnamadaya Purnamevavashishyate', meaning:'That is whole; this is whole. From wholeness emerges wholeness — and yet wholeness remains.', meaningHindi:'सब पूर्ण है — पूर्णता से पूर्णता ही प्रकट होती है।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'Invocation of completeness.', howToChant:'As a peace invocation.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'asato-ma-sadgamaya', name:'Asato Ma Sadgamaya', script:'असतो मा सद्गमय । तमसो मा ज्योतिर्गमय । मृत्योर्मा अमृतं गमय ॥', transliteration:'Asato Ma Sadgamaya Tamaso Ma Jyotirgamaya Mrityorma Amritam Gamaya', meaning:'Lead me from untruth to truth, darkness to light, death to immortality.', meaningHindi:'असत् से सत् की ओर, अंधकार से प्रकाश की ओर ले चलो।', deity:'Universal', tradition:'Vedic', category:'universal', benefits:'Universal evening prayer.', howToChant:'In Sandhya or before sleep.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'om-sahana-vavatu', name:'Om Sahana Vavatu', script:'ॐ सहनाववतु । सहनौ भुनक्तु । सह वीर्यं करवावहै । तेजस्विनावधीतमस्तु मा विद्विषावहै ॥', transliteration:'Om Saha Nau Vavatu Saha Nau Bhunaktu Saha Viryam Karavavahai', meaning:'May we be protected together, nourished together — let us strive together with vigor.', meaningHindi:'हम सब साथ रक्षित हों, साथ पोषित हों, मिलकर ऊर्जा से कार्य करें।', deity:'Universal', tradition:'Vedic', category:'universal', benefits:'Teacher‑student peace invocation.', howToChant:'Before study or together with a partner.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'lokah-samastah-sukhino-bhavantu', name:'Lokah Samastah Sukhino Bhavantu', script:'लोकाः समस्ताः सुखिनो भवन्तु', transliteration:'Lokah Samastah Sukhino Bhavantu', meaning:'May all beings everywhere be happy and free.', meaningHindi:'सभी प्राणी सुखी हों।', deity:'Universal', tradition:'Universal', category:'universal', benefits:'Cultivates compassion and universal love.', howToChant:'After meditation; closing prayer.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },

  // ───── KALI ─────
  { id:'om-krim-kalyai-namah', name:'Om Krim Kalyai Namah', script:'ॐ क्रीं कालिकायै नमः', transliteration:'Om Krim Kalyai Namah', meaning:'Beej mantra of Goddess Kali.', meaningHindi:'काली जी का बीज।', deity:'Kali', tradition:'Shakta', category:'devi', benefits:'Burns away ego; transformative power.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'jai-kali-mata', name:'Jai Kali Mata', script:'जय काली माता', transliteration:'Jai Kali Mata', meaning:'Victory to Mother Kali.', meaningHindi:'काली माता की जय।', deity:'Kali', tradition:'Shakta', category:'devi', benefits:'Devotional invocation.', howToChant:'Aloud.', defaultMusic:'gayatri', language:'Hindi', featured:false },
  { id:'om-hrim-shrim-krim-parameshvari', name:'Om Hrim Shrim Krim Parameshvari Swaha', script:'ॐ ह्रीं श्रीं क्रीं परमेश्वरि स्वाहा', transliteration:'Om Hrim Shrim Krim Parameshvari Swaha', meaning:'Tantric beej combination invoking the Supreme Goddess.', meaningHindi:'परमेश्वरी देवी के बीज मन्त्र।', deity:'Kali', tradition:'Shakta', category:'devi', benefits:'Awakens shakti.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },

  // ───── KARTIKEYA / MURUGAN ─────
  { id:'om-saravanabhavaya-namah', name:'Om Saravanabhavaya Namah', script:'ॐ सरवणभवाय नमः', transliteration:'Om Saravanabhavaya Namah', meaning:'Salutations to Saravanabhava (Murugan).', meaningHindi:'सरवणभव (कार्तिकेय) को नमन।', deity:'Murugan', tradition:'Shaiva', category:'shiva', benefits:'Removes negative forces; awakens valor.', howToChant:'108 times.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'om-skandaya-namah', name:'Om Skandaya Namah', script:'ॐ स्कन्दाय नमः', transliteration:'Om Skandaya Namah', meaning:'Salutations to Skanda — son of Shiva.', meaningHindi:'स्कन्द को नमन।', deity:'Murugan', tradition:'Shaiva', category:'shiva', benefits:'Awakens valor and protection.', howToChant:'108 times.', defaultMusic:'shiv-tandav', language:'Sanskrit', featured:false },
  { id:'sharavana-bhava', name:'Om Sha Ra Va Na Ba Va', script:'ஓம் சரவணபவ', transliteration:'Om Sha Ra Va Na Ba Va', meaning:'The six sacred syllables of Murugan.', meaningHindi:'षडक्षरी मुरुगन मन्त्र।', deity:'Murugan', tradition:'Shaiva', category:'shiva', benefits:'Removes obstacles; awakens valor.', howToChant:'108 times.', defaultMusic:'shiv-tandav', language:'Tamil', featured:false },
  { id:'vel-vel-murugan', name:'Vel Vel Murugan', script:'வேல் வேல் முருகன்', transliteration:'Vel Vel Murugan', meaning:'Glory to Murugan, wielder of the divine spear.', meaningHindi:'वेल धारी मुरुगन की जय।', deity:'Murugan', tradition:'Shaiva', category:'shiva', benefits:'Devotional Tamil chant.', howToChant:'Aloud.', defaultMusic:'shiv-tandav', language:'Tamil', featured:false },

  // ───── AYYAPPA ─────
  { id:'swamiye-saranam-ayyappa', name:'Swamiye Saranam Ayyappa', script:'സ്വാമിയേ ശരണം അയ്യപ്പ', transliteration:'Swamiye Saranam Ayyappa', meaning:'Lord, I take refuge in Ayyappa.', meaningHindi:'स्वामी अय्यप्पा की शरण में।', deity:'Ayyappa', tradition:'Hindu', category:'universal', benefits:'Devotional chant during Sabarimala pilgrimage.', howToChant:'Aloud during the 41‑day vrata.', defaultMusic:'om-chant', language:'Malayalam', featured:false },

  // ───── DATTATREYA ─────
  { id:'om-draam-dattatreyaya-namah', name:'Om Draam Dattatreyaya Namah', script:'ॐ द्रां दत्तात्रेयाय नमः', transliteration:'Om Draam Dattatreyaya Namah', meaning:'Salutations to Dattatreya — embodiment of Brahma, Vishnu, Shiva.', meaningHindi:'दत्तात्रेय को नमन।', deity:'Dattatreya', tradition:'Universal', category:'guru', benefits:'Bestows guru‑grace; removes obstacles.', howToChant:'108 times on Thursdays.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'digambara-digambara', name:'Digambara Digambara Shripad Vallabha', script:'दिगम्बर दिगम्बर श्रीपाद वल्लभ दिगम्बर', transliteration:'Digambara Digambara Shripad Vallabha Digambara', meaning:'Devotional invocation of Dattatreya as Shripad Vallabha.', meaningHindi:'दिगम्बर दिगम्बर श्रीपाद वल्लभ।', deity:'Dattatreya', tradition:'Universal', category:'guru', benefits:'Awakens guru bhakti.', howToChant:'In melody.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },

  // ───── KUBERA ─────
  { id:'om-yakshaya-kuberaya-namah', name:'Om Yakshaya Kuberaya Vaishravanaya Namah', script:'ॐ यक्षाय कुबेराय वैश्रवणाय धनधान्याधिपतये धनधान्य समृद्धिं मे देहि दापय स्वाहा', transliteration:'Om Yakshaya Kuberaya Vaishravanaya Namah', meaning:'Salutations to Kubera, Lord of wealth.', meaningHindi:'कुबेर को नमन।', deity:'Kubera', tradition:'Hindu', category:'universal', benefits:'Attracts wealth and prosperity.', howToChant:'108 times on Wednesdays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-hreem-shreem-kuberaya-namah', name:'Om Hreem Shreem Hreem Kuberaya Namah', script:'ॐ ह्रीं श्रीं ह्रीं कुबेराय नमः', transliteration:'Om Hreem Shreem Hreem Kuberaya Namah', meaning:'Beej combination invoking Kubera.', meaningHindi:'कुबेर के बीज मन्त्र।', deity:'Kubera', tradition:'Hindu', category:'universal', benefits:'Removes financial obstacles.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },

  // ───── NAVAGRAHA ─────
  { id:'om-suryaya-namah-graha', name:'Om Suryaya Namah (Surya / Sun)', script:'ॐ सूर्याय नमः', transliteration:'Om Suryaya Namah', meaning:'Honors the Sun (Navagraha).', meaningHindi:'सूर्य ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Strengthens Sun in horoscope.', howToChant:'Sunday, 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-chandraya-namah', name:'Om Chandraya Namah (Chandra / Moon)', script:'ॐ चंद्राय नमः', transliteration:'Om Chandraya Namah', meaning:'Honors the Moon.', meaningHindi:'चंद्र ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Calms emotions; strengthens Moon.', howToChant:'Monday, 108 times.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'om-mangalaya-namah', name:'Om Mangalaya Namah (Mangal / Mars)', script:'ॐ मंगलाय नमः', transliteration:'Om Mangalaya Namah', meaning:'Honors Mars.', meaningHindi:'मंगल ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Strengthens Mars; courage.', howToChant:'Tuesday, 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-budhaya-namah', name:'Om Budhaya Namah (Budha / Mercury)', script:'ॐ बुधाय नमः', transliteration:'Om Budhaya Namah', meaning:'Honors Mercury.', meaningHindi:'बुध ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Sharpens intellect; communication.', howToChant:'Wednesday, 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-gurave-namah', name:'Om Gurave Namah (Guru / Jupiter)', script:'ॐ गुरवे नमः', transliteration:'Om Gurave Namah', meaning:'Honors Jupiter (Brihaspati).', meaningHindi:'गुरु ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Wisdom; expansion; good fortune.', howToChant:'Thursday, 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-shukraya-namah', name:'Om Shukraya Namah (Shukra / Venus)', script:'ॐ शुक्राय नमः', transliteration:'Om Shukraya Namah', meaning:'Honors Venus.', meaningHindi:'शुक्र ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Brings love; comforts; arts.', howToChant:'Friday, 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-shanaye-namah', name:'Om Shanaye Namah (Shani / Saturn)', script:'ॐ शनये नमः', transliteration:'Om Shanaye Namah', meaning:'Honors Saturn.', meaningHindi:'शनि ग्रह को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Discipline; karma resolution.', howToChant:'Saturday, 108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-rahave-namah', name:'Om Rahave Namah (Rahu)', script:'ॐ राहवे नमः', transliteration:'Om Rahave Namah', meaning:'Honors Rahu (north node).', meaningHindi:'राहु को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Mitigates Rahu effects.', howToChant:'108 times on Saturdays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'om-ketave-namah', name:'Om Ketave Namah (Ketu)', script:'ॐ केतवे नमः', transliteration:'Om Ketave Namah', meaning:'Honors Ketu (south node).', meaningHindi:'केतु को नमन।', deity:'Navagraha', tradition:'Vedic', category:'navagraha', benefits:'Spiritual liberation; mitigates Ketu.', howToChant:'108 times on Tuesdays.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },

  // ───── BUDDHIST ─────
  { id:'om-mani-padme-hum', name:'Om Mani Padme Hum', script:'ॐ मणि पद्मे हूँ', transliteration:'Om Mani Padme Hum', meaning:'The jewel in the lotus — Tibetan mantra of compassion.', meaningHindi:'कमल में मणि — करुणा का मन्त्र।', deity:'Avalokiteshvara', tradition:'Buddhist', category:'buddhist', benefits:'Awakens compassion; purifies negative karma.', howToChant:'Slowly, holding compassion in heart.', defaultMusic:'bansuri', language:'Sanskrit', featured:true },
  { id:'namo-buddhaya', name:'Namo Buddhaya', script:'नमो बुद्धाय', transliteration:'Namo Buddhaya', meaning:'I bow to the Awakened One.', meaningHindi:'बुद्ध को नमन।', deity:'Buddha', tradition:'Buddhist', category:'buddhist', benefits:'Cultivates awareness, compassion, equanimity.', howToChant:'Sit in mindful silence between repetitions.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'buddham-sharanam-gacchami', name:'Buddham Sharanam Gacchami', script:'बुद्धं शरणं गच्छामि', transliteration:'Buddham Sharanam Gacchami', meaning:'I take refuge in the Buddha.', meaningHindi:'मैं बुद्ध की शरण लेता हूँ।', deity:'Buddha', tradition:'Buddhist', category:'buddhist', benefits:'First of the Three Refuges.', howToChant:'Three times before practice.', defaultMusic:'bansuri', language:'Pali', featured:false },
  { id:'dhammam-sharanam-gacchami', name:'Dhammam Sharanam Gacchami', script:'धम्मं शरणं गच्छामि', transliteration:'Dhammam Sharanam Gacchami', meaning:'I take refuge in the Dharma.', meaningHindi:'मैं धर्म की शरण लेता हूँ।', deity:'Buddha', tradition:'Buddhist', category:'buddhist', benefits:'Second of the Three Refuges.', howToChant:'Three times before practice.', defaultMusic:'bansuri', language:'Pali', featured:false },
  { id:'sangham-sharanam-gacchami', name:'Sangham Sharanam Gacchami', script:'संघं शरणं गच्छामि', transliteration:'Sangham Sharanam Gacchami', meaning:'I take refuge in the Sangha.', meaningHindi:'मैं संघ की शरण लेता हूँ।', deity:'Buddha', tradition:'Buddhist', category:'buddhist', benefits:'Third of the Three Refuges.', howToChant:'Three times before practice.', defaultMusic:'bansuri', language:'Pali', featured:false },
  { id:'gate-gate-paragate', name:'Gate Gate Paragate', script:'गते गते पारगते पारसंगते बोधि स्वाहा', transliteration:'Gate Gate Paragate Parasamgate Bodhi Svaha', meaning:'Gone, gone, beyond, fully beyond — awakening, hail! (Heart Sutra mantra).', meaningHindi:'हृदय सूत्र का अन्तिम मन्त्र।', deity:'Prajnaparamita', tradition:'Buddhist', category:'buddhist', benefits:'Awakens prajna (transcendent wisdom).', howToChant:'Slowly with reflection.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'om-tare-tuttare-ture-swaha', name:'Om Tare Tuttare Ture Swaha', script:'ॐ तारे तुत्तारे तुरे स्वाहा', transliteration:'Om Tare Tuttare Ture Swaha', meaning:'Mantra of Green Tara — swift liberator from fears.', meaningHindi:'हरित तारा का मन्त्र।', deity:'Tara', tradition:'Buddhist', category:'buddhist', benefits:'Removes fear; awakens grace.', howToChant:'108 times.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'om-vajrasattva-hum', name:'Om Vajrasattva Hum', script:'ॐ वज्रसत्व हूँ', transliteration:'Om Vajrasattva Hum', meaning:'Brief Vajrasattva mantra — purification.', meaningHindi:'वज्रसत्व का संक्षिप्त मन्त्र।', deity:'Vajrasattva', tradition:'Buddhist', category:'buddhist', benefits:'Purifies negative karma.', howToChant:'108 times.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'om-ami-dewa-hrih', name:'Om Ami Dewa Hrih', script:'ॐ अमि देव ह्रीः', transliteration:'Om Ami Dewa Hrih', meaning:'Mantra of Amitabha Buddha (Pure Land).', meaningHindi:'अमिताभ बुद्ध का मन्त्र।', deity:'Amitabha', tradition:'Buddhist', category:'buddhist', benefits:'Connection to Pure Land.', howToChant:'108 times.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },
  { id:'namo-tassa-bhagavato', name:'Namo Tassa Bhagavato', script:'नमो तस्स भगवतो अरहतो सम्मासम्बुद्धस्स', transliteration:'Namo Tassa Bhagavato Arahato Samma Sambuddhassa', meaning:'Honor to the Blessed One, the Worthy, the Fully Self‑Awakened.', meaningHindi:'भगवान बुद्ध को त्रिवार नमन।', deity:'Buddha', tradition:'Buddhist', category:'buddhist', benefits:'Theravada opening salutation.', howToChant:'Three times before practice.', defaultMusic:'bansuri', language:'Pali', featured:false },

  // ───── JAIN ─────
  { id:'navkar-mantra', name:'Navkar Mantra (Namokar)', script:'णमो अरिहंताणं । णमो सिद्धाणं । णमो आयरियाणं । णमो उवज्झायाणं । णमो लोए सव्व साहूणं ॥', transliteration:'Namo Arihantanam Namo Siddhanam Namo Ayariyanam Namo Uvajjhayanam Namo Loe Savva Sahunam', meaning:'I bow to the Arihants, Siddhas, Acharyas, Upadhyayas, and all sadhus.', meaningHindi:'पंच परमेष्ठी को नमन।', deity:'Universal', tradition:'Jain', category:'jain', benefits:'Foundational Jain mantra; cultivates non‑violence.', howToChant:'108 times daily.', defaultMusic:'om-chant', language:'Prakrit', featured:false },
  { id:'jai-jinendra', name:'Jai Jinendra', script:'जय जिनेन्द्र', transliteration:'Jai Jinendra', meaning:'Glory to the conqueror of inner passions.', meaningHindi:'जिनेन्द्र देव की जय।', deity:'Universal', tradition:'Jain', category:'jain', benefits:'Cultivates equanimity and respect.', howToChant:'As greeting and remembrance.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'om-hreem-arham', name:'Om Hreem Arham', script:'ॐ ह्रीं अर्हम्', transliteration:'Om Hreem Arham', meaning:'Beej combination honoring the Arihants.', meaningHindi:'अर्हम् बीज मन्त्र।', deity:'Universal', tradition:'Jain', category:'jain', benefits:'Awakens inner victory.', howToChant:'108 times.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'arham', name:'Arham', script:'अर्हम्', transliteration:'Arham', meaning:'The worthy one (sound‑form of liberation).', meaningHindi:'अर्हम् — मुक्ति का सूत्र।', deity:'Universal', tradition:'Jain', category:'jain', benefits:'Used in Preksha meditation.', howToChant:'In silent meditation.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'micchami-dukkadam', name:'Micchami Dukkadam', script:'मिच्छामि दुक्कडम्', transliteration:'Micchami Dukkadam', meaning:'May my faults be forgiven (Samvatsari).', meaningHindi:'मेरे दोष क्षमा हों।', deity:'Universal', tradition:'Jain', category:'jain', benefits:'Cultivates forgiveness.', howToChant:'On Samvatsari (Paryushan).', defaultMusic:'om-chant', language:'Prakrit', featured:false },
  { id:'parasparo-upagraho-jivanam', name:'Parasparo Upagraho Jivanam', script:'परस्परोपग्रहो जीवानाम्', transliteration:'Parasparo Upagraho Jivanam', meaning:'Souls render service to one another (Tattvartha Sutra).', meaningHindi:'सब जीव परस्पर सहायक हैं।', deity:'Universal', tradition:'Jain', category:'jain', benefits:'Cultivates non‑violence and interdependence.', howToChant:'In daily reflection.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },

  // ───── SIKH ─────
  { id:'waheguru', name:'Waheguru', script:'ਵਾਹਿਗੁਰੂ', transliteration:'Waheguru', meaning:'Wondrous Lord — primary Sikh naam simran.', meaningHindi:'वाहिगुरू — सिख गुरुओं का प्राथमिक नाम।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Naam simran; brings deep peace.', howToChant:'On a 108‑bead simran mala.', defaultMusic:'bansuri', language:'Punjabi', featured:true },
  { id:'ik-onkar', name:'Ik Onkar', script:'ੴ', transliteration:'Ik Onkar', meaning:'There is one God — opening of Mool Mantar.', meaningHindi:'एक ओंकार — मूल मन्त्र की प्रथम पंक्ति।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Foundational realization of oneness.', howToChant:'In meditation.', defaultMusic:'bansuri', language:'Punjabi', featured:false },
  { id:'sat-nam', name:'Sat Nam', script:'ਸਤਿ ਨਾਮੁ', transliteration:'Sat Nam', meaning:'True Name.', meaningHindi:'सत् नाम — सत्य का स्मरण।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Anchors awareness in truth.', howToChant:'In Kundalini Yoga; with breath.', defaultMusic:'bansuri', language:'Punjabi', featured:false },
  { id:'satnam-waheguru', name:'Satnam Waheguru', script:'ਸਤਿ ਨਾਮੁ ਵਾਹਿਗੁਰੂ', transliteration:'Satnam Waheguru', meaning:'True Name — Wondrous Lord.', meaningHindi:'सत् नाम वाहिगुरू।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Deep simran; peace.', howToChant:'In meditation.', defaultMusic:'bansuri', language:'Punjabi', featured:false },
  { id:'mool-mantar', name:'Mool Mantar', script:'ੴ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ ॥', transliteration:'Ik Onkar Sat Nam Karta Purakh Nirbhau Nirvair Akal Murat Ajooni Saibhang Gur Prasad', meaning:'The foundational creed at the start of Guru Granth Sahib.', meaningHindi:'गुरु ग्रन्थ साहिब का मूल मन्त्र।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Foundation of Sikh faith.', howToChant:'At Amrit Vela (pre‑dawn).', defaultMusic:'bansuri', language:'Punjabi', featured:false },
  { id:'jo-bole-so-nihal', name:'Jo Bole So Nihal', script:'ਜੋ ਬੋਲੇ ਸੋ ਨਿਹਾਲ ॥ ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ॥', transliteration:'Jo Bole So Nihal — Sat Sri Akal', meaning:'One who speaks shall be blessed — Truth is the timeless Lord.', meaningHindi:'जो बोले सो निहाल — सत श्री अकाल।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Sikh battle cry of devotion.', howToChant:'Aloud as call and response.', defaultMusic:'bansuri', language:'Punjabi', featured:false },
  { id:'sat-sri-akal', name:'Sat Sri Akal', script:'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', transliteration:'Sat Sri Akal', meaning:'Truth is the timeless Lord.', meaningHindi:'सत् श्री अकाल।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Sikh greeting and remembrance.', howToChant:'In greeting and meditation.', defaultMusic:'bansuri', language:'Punjabi', featured:false },
  { id:'sarbat-da-bhala', name:'Sarbat Da Bhala', script:'ਸਰਬੱਤ ਦਾ ਭਲਾ', transliteration:'Sarbat Da Bhala', meaning:'May the welfare of all prevail (Sikh ardas closing).', meaningHindi:'सबका भला हो।', deity:'Universal', tradition:'Sikh', category:'sikh', benefits:'Cultivates universal goodwill.', howToChant:'In ardas / closing prayer.', defaultMusic:'bansuri', language:'Punjabi', featured:false },

  // ───── SOUTH INDIAN / TAMIL ─────
  { id:'om-namasivaya-tamil', name:'Om Namasivaya (Tamil)', script:'ஓம் நமசிவாய', transliteration:'Om Namasivaya', meaning:'Tamil form of the Panchakshara — salutations to Shiva.', meaningHindi:'पंचाक्षरी का तमिल रूप।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Same as Om Namah Shivaya.', howToChant:'108 times.', defaultMusic:'shiv-tandav', language:'Tamil', featured:false },
  { id:'arunachala-shiva', name:'Arunachala Shiva', script:'அருணாசல சிவ அருணாசல சிவ', transliteration:'Arunachala Shiva Arunachala Shiva', meaning:'Hill of fire — Shiva of Arunachala (Ramana Maharshi\'s mantra).', meaningHindi:'अरुणाचल शिव।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Awakens self‑inquiry.', howToChant:'In silent recollection.', defaultMusic:'shiv-tandav', language:'Tamil', featured:false },
  { id:'vel-vel-murugan-tamil', name:'Vel Vel Murugan', script:'வேல் வேல் முருகன்', transliteration:'Vel Vel Murugan', meaning:'Glory to Murugan with the spear.', meaningHindi:'मुरुगन की जय।', deity:'Murugan', tradition:'Shaiva', category:'shiva', benefits:'Devotional Tamil chant.', howToChant:'Aloud.', defaultMusic:'shiv-tandav', language:'Tamil', featured:false },
  { id:'thiru-neela-kantam', name:'Thiru Neela Kantam', script:'திரு நீல கண்டம்', transliteration:'Thiru Neela Kantam', meaning:'The auspicious blue throat — Shiva who held the poison.', meaningHindi:'श्री नीलकण्ठ शिव।', deity:'Shiva', tradition:'Shaiva', category:'shiva', benefits:'Protection from harm.', howToChant:'108 times.', defaultMusic:'shiv-tandav', language:'Tamil', featured:false },

  // ───── GURU / SPIRITUAL ─────
  { id:'om-guru-om', name:'Om Guru Om', script:'ॐ गुरु ॐ', transliteration:'Om Guru Om', meaning:'Salutation to the inner Guru.', meaningHindi:'गुरु को नमन।', deity:'Universal', tradition:'Universal', category:'guru', benefits:'Awakens guru bhakti.', howToChant:'108 times.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'guru-brahma-guru-vishnu', name:'Guru Brahma Guru Vishnu', script:'गुरुर्ब्रह्मा गुरुर्विष्णुः गुरुर्देवो महेश्वरः । गुरुसाक्षात् परब्रह्म तस्मै श्रीगुरवे नमः ॥', transliteration:'Guru Brahma Guru Vishnu Gurudevo Maheshwarah Guru Sakshat Parabrahma Tasmai Shri Gurave Namah', meaning:'Guru is Brahma, Vishnu, Maheshwara — the Supreme. Salutations to the Guru.', meaningHindi:'गुरु ब्रह्मा, विष्णु और महेश्वर हैं।', deity:'Universal', tradition:'Universal', category:'guru', benefits:'Awakens guru bhakti.', howToChant:'On Guru Purnima or daily.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'om-shri-gurave-namah', name:'Om Shri Gurave Namah', script:'ॐ श्री गुरवे नमः', transliteration:'Om Shri Gurave Namah', meaning:'Salutations to the Guru.', meaningHindi:'गुरु को नमन।', deity:'Universal', tradition:'Universal', category:'guru', benefits:'Removes ignorance.', howToChant:'108 times.', defaultMusic:'om-chant', language:'Sanskrit', featured:false },
  { id:'jai-gurudev', name:'Jai Gurudev', script:'जय गुरुदेव', transliteration:'Jai Gurudev', meaning:'Victory to the Guru.', meaningHindi:'जय गुरुदेव।', deity:'Universal', tradition:'Universal', category:'guru', benefits:'Devotional chant.', howToChant:'As greeting and chant.', defaultMusic:'om-chant', language:'Hindi', featured:false },
  { id:'sat-chit-ananda', name:'Sat Chit Ananda', script:'सत्-चित्-आनन्द', transliteration:'Sat Chit Ananda', meaning:'Existence — Consciousness — Bliss (the nature of Brahman).', meaningHindi:'सत्-चित्-आनन्द — ब्रह्म का स्वरूप।', deity:'Universal', tradition:'Vedanta', category:'universal', benefits:'Identifies awareness with the Self.', howToChant:'In silent meditation.', defaultMusic:'bansuri', language:'Sanskrit', featured:false },

  // ───── VAISHNAV REGIONAL ─────
  { id:'jai-jai-vitthal', name:'Jai Jai Vitthal Jai Hari Vitthal', script:'जय जय विठ्ठल जय हरि विठ्ठल', transliteration:'Jai Jai Vitthal Jai Hari Vitthal', meaning:'Glory to Vitthal of Pandharpur — Maharashtra\'s beloved form of Vishnu.', meaningHindi:'विठ्ठल नाम स्मरण।', deity:'Vishnu', tradition:'Vaishnava', category:'krishna', benefits:'Awakens Varkari devotion.', howToChant:'In abhang style.', defaultMusic:'krishna-flute', language:'Marathi', featured:false },
  { id:'panduranga-panduranga', name:'Panduranga Panduranga', script:'पांडुरंगा पांडुरंगा', transliteration:'Panduranga Panduranga', meaning:'Calling Panduranga (Vitthal) of Pandharpur.', meaningHindi:'पांडुरंग का स्मरण।', deity:'Vishnu', tradition:'Vaishnava', category:'krishna', benefits:'Devotional kirtan.', howToChant:'In melody.', defaultMusic:'krishna-flute', language:'Marathi', featured:false },
  { id:'swaminarayan-swaminarayan', name:'Swaminarayan Swaminarayan', script:'स्वामिनारायण स्वामिनारायण', transliteration:'Swaminarayan Swaminarayan', meaning:'Devotional repetition of Swaminarayan name.', meaningHindi:'स्वामिनारायण नाम स्मरण।', deity:'Swaminarayan', tradition:'Vaishnava', category:'krishna', benefits:'Sampraday core simran.', howToChant:'On a Tulsi mala.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'jai-swaminarayan', name:'Jai Swaminarayan', script:'जय स्वामिनारायण', transliteration:'Jai Swaminarayan', meaning:'Glory to Lord Swaminarayan.', meaningHindi:'जय स्वामिनारायण।', deity:'Swaminarayan', tradition:'Vaishnava', category:'krishna', benefits:'Devotional greeting.', howToChant:'As greeting and chant.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },
  { id:'jay-akshar-purushottam', name:'Jay Akshar Purushottam', script:'जय अक्षर पुरुषोत्तम', transliteration:'Jay Akshar Purushottam', meaning:'Glory to the eternal Akshar and Purushottam.', meaningHindi:'जय अक्षर पुरुषोत्तम।', deity:'Swaminarayan', tradition:'Vaishnava', category:'krishna', benefits:'BAPS Swaminarayan core chant.', howToChant:'In daily darshan.', defaultMusic:'krishna-flute', language:'Sanskrit', featured:false },

  // ───── SHAKTA REGIONAL ─────
  { id:'jai-ambe-mata', name:'Jai Ambe Mata', script:'जय अंबे माता', transliteration:'Jai Ambe Mata', meaning:'Glory to Mother Amba.', meaningHindi:'जय अंबे माता।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Devotional Mata chant.', howToChant:'In aarti.', defaultMusic:'gayatri', language:'Hindi', featured:false },
  { id:'jai-bhavani', name:'Jai Bhavani', script:'जय भवानी', transliteration:'Jay Bhavani', meaning:'Glory to Bhavani — fierce form of Devi (Maratha rallying cry).', meaningHindi:'जय भवानी।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Awakens valor.', howToChant:'Aloud.', defaultMusic:'gayatri', language:'Marathi', featured:false },
  { id:'jai-jai-jagdambe', name:'Jai Jai Jagdambe', script:'जय जय जगदम्बे', transliteration:'Jai Jai Jagdambe', meaning:'Glory to the Mother of the Universe.', meaningHindi:'जगदम्बे माता की जय।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Devotional kirtan.', howToChant:'In melody.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
  { id:'jai-bahucharaji', name:'Jai Bahucharaji', script:'જય બહુચરાજી', transliteration:'Jai Bahucharaji', meaning:'Glory to Bahuchara Mata — Gujarat shakta tradition.', meaningHindi:'बहुचरा माता की जय।', deity:'Durga', tradition:'Shakta', category:'devi', benefits:'Regional devotional chant.', howToChant:'In Gujarati garba.', defaultMusic:'gayatri', language:'Gujarati', featured:false },
  { id:'kolhapur-ambe-jai', name:'Kolhapur Ambe Jai', script:'कोल्हापुर अंबे जय', transliteration:'Kolhapur Ambe Jai', meaning:'Glory to Mahalakshmi of Kolhapur.', meaningHindi:'कोल्हापुर अंबे माँ की जय।', deity:'Lakshmi', tradition:'Shakta', category:'devi', benefits:'Maharashtrian devotional chant.', howToChant:'In aarti.', defaultMusic:'gayatri', language:'Marathi', featured:false },
  { id:'om-aim-klim-sauh', name:'Om Aim Klim Sauh (Tripura Sundari)', script:'ॐ ऐं क्लीं सौः', transliteration:'Om Aim Klim Sauh', meaning:'Bala Tripura Sundari beej — auspicious goddess of beauty.', meaningHindi:'त्रिपुरसुंदरी बाला बीज मन्त्र।', deity:'Tripura Sundari', tradition:'Shakta', category:'devi', benefits:'Awakens auspicious shakti.', howToChant:'108 times.', defaultMusic:'gayatri', language:'Sanskrit', featured:false },
];

// Categories used in Mantra Library filter UI
export const CATEGORIES = [
  { id:'all',       label:'All' },
  { id:'shiva',     label:'Shiva' },
  { id:'vishnu',    label:'Vishnu' },
  { id:'ram',       label:'Ram' },
  { id:'krishna',   label:'Krishna / Radhe' },
  { id:'hanuman',   label:'Hanuman' },
  { id:'ganesha',   label:'Ganesh' },
  { id:'devi',      label:'Devi / Lakshmi / Saraswati' },
  { id:'surya',     label:'Surya / Gayatri' },
  { id:'navagraha', label:'Navagraha' },
  { id:'buddhist',  label:'Buddhist' },
  { id:'jain',      label:'Jain' },
  { id:'sikh',      label:'Sikh' },
  { id:'guru',      label:'Guru / Vedanta' },
  { id:'universal', label:'Universal / Vedic' },
];

export const FEATURED_MANTRAS = ALL_MANTRAS.filter(m => m.featured);
export const getMantraById = (id) => ALL_MANTRAS.find(m => m.id === id);
export const getMantrasByCategory = (cat, excludeId = null) =>
  ALL_MANTRAS.filter(m => m.category === cat && m.id !== excludeId);

// Backwards-compat exports (used by older imports)
export const MANTRAS = ALL_MANTRAS;
export const DEITIES = CATEGORIES.map(c => c.label);
